name:                attoparsec-ip
version:             0.0.2
github:              "athanclark/attoparsec-ip"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 (c) Local Cooking Inc."

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Parse IP data types with attoparsec
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/purescript-iso#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 4.11
- attoparsec
- ip >= 1.3.0 && < 1.4.0
- vector

library:
  source-dirs: src

tests:
  purescript-iso-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec-ip
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - ip
    - attoparsec
    - text
